#!/usr/bin/env bash
set -euo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly VM_NAMES=(lab1-pg1 lab1-pg2 lab1-pg3)
readonly VM_HOSTNAMES=(pg1.lab.example pg2.lab.example pg3.lab.example)
readonly VM_CPUS="${VM_CPUS:-2}"
readonly VM_MEMORY_GIB="${VM_MEMORY_GIB:-4}"
readonly VM_DISK_GIB="${VM_DISK_GIB:-20}"
readonly LIMA_TEMPLATE="${LIMA_TEMPLATE:-$SCRIPT_DIR/../rocky-9.8.yaml}"
readonly LIMA_NETWORK="${LIMA_NETWORK:-lima:shared}"
readonly ENV_FILE="$SCRIPT_DIR/../.env"
readonly HOSTS_FILE="/etc/hosts"
readonly HOSTS_BEGIN="# BEGIN simple-patroni-npgsql-lab lab1"
readonly HOSTS_END="# END simple-patroni-npgsql-lab lab1"

usage() {
  cat <<'EOF'
Usage: ./scripts/vms.sh create|destroy|status|hostnames

create   Create (if needed) and start lab1-pg1, lab1-pg2, and lab1-pg3.
destroy  Permanently delete those three VMs and their disks.
status   Display the Lima status of the Lab 1 VMs.
hostnames  Update the marked Lab 1 block in macOS /etc/hosts.

Optional environment overrides:
  VM_CPUS=2 VM_MEMORY_GIB=4 VM_DISK_GIB=20 LIMA_TEMPLATE=rocky-9.8.yaml
  LIMA_NETWORK=lima:shared
EOF
}

require_lima() {
  command -v limactl >/dev/null 2>&1 || {
    echo "limactl is required. Install Lima first: brew install lima" >&2
    exit 1
  }
}

require_network() {
  if [[ "$LIMA_NETWORK" == "lima:shared" ]] && ! limactl sudoers --check >/dev/null 2>&1; then
    echo "Lima's shared socket_vmnet network is not configured." >&2
    echo "Follow https://lima-vm.io/docs/config/network/vmnet/ and rerun this command." >&2
    exit 1
  fi
}

instance_exists() {
  limactl list --quiet | grep -Fxq "$1"
}

vm_ip() {
  local vm_name="$1" address=""

  # limactl start returns before the shared network has necessarily leased an
  # address, and an empty value here only fails much later in the inventory.
  for _ in {1..30}; do
    address="$(limactl shell --tty=false "$vm_name" sh -ceu \
      'ip -4 -o addr show dev lima0 | grep -oE "[0-9.]+/[0-9]+" | cut -d/ -f1' 2>/dev/null || true)"
    if [[ -n "$address" ]]; then
      printf '%s\n' "$address"
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for a lima0 shared-network address on $vm_name" >&2
  return 1
}

write_env_file() {
  local -a vm_ips=("$@")

  {
    printf '%s\n' '# Generated by scripts/vms.sh. Do not commit this file.'
    printf '%s\n' 'PGPORT=5432'
    for index in "${!VM_NAMES[@]}"; do
      printf 'PG%d_HOST=%s\n' "$((index + 1))" "${VM_HOSTNAMES[index]}"
      printf 'PG%d_IP=%s\n' "$((index + 1))" "${vm_ips[index]}"
    done
    printf 'PGHOSTS=%s:5432,%s:5432,%s:5432\n' \
      "${VM_HOSTNAMES[0]}" "${VM_HOSTNAMES[1]}" "${VM_HOSTNAMES[2]}"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "Wrote connection details: $ENV_FILE"
}

rewrite_hosts_without_lab_block() {
  local destination="$1"
  awk -v begin="$HOSTS_BEGIN" -v end="$HOSTS_END" '
    $0 == begin { in_block = 1; next }
    $0 == end { in_block = 0; next }
    !in_block { print }
  ' "$HOSTS_FILE" > "$destination"
}

configure_hostnames() {
  local -a vm_ips=()
  local index vm_name hosts_without_block updated_hosts

  for vm_name in "${VM_NAMES[@]}"; do
    vm_ips+=("$(vm_ip "$vm_name")")
  done
  write_env_file "${vm_ips[@]}"

  hosts_without_block="$(mktemp "${TMPDIR:-/tmp}/lab1-hosts.XXXXXX")"
  updated_hosts="$(mktemp "${TMPDIR:-/tmp}/lab1-hosts-updated.XXXXXX")"
  rewrite_hosts_without_lab_block "$hosts_without_block"
  {
    cat "$hosts_without_block"
    printf '\n%s\n' "$HOSTS_BEGIN"
    for index in "${!VM_NAMES[@]}"; do
      printf '%s %s\n' "${vm_ips[index]}" "${VM_HOSTNAMES[index]}"
    done
    printf '%s\n' "$HOSTS_END"
  } > "$updated_hosts"
  local -a sudo_options=(-n)
  [[ "${LAB1_INTERACTIVE_SUDO:-0}" == 1 ]] && sudo_options=()
  if sudo "${sudo_options[@]}" cp "$updated_hosts" "$HOSTS_FILE"; then
    echo "Configured hostnames: ${VM_HOSTNAMES[*]}"
  else
    echo "Host aliases were not changed because macOS sudo needs an interactive password." >&2
    echo "Run 'make configure_hostnames' from a terminal when you want to add them." >&2
  fi
  rm -f "$hosts_without_block" "$updated_hosts"
}

remove_hostnames() {
  local hosts_without_block

  if ! grep -Fqx "$HOSTS_BEGIN" "$HOSTS_FILE"; then
    return
  fi
  hosts_without_block="$(mktemp "${TMPDIR:-/tmp}/lab1-hosts.XXXXXX")"
  rewrite_hosts_without_lab_block "$hosts_without_block"
  local -a sudo_options=(-n)
  [[ "${LAB1_INTERACTIVE_SUDO:-0}" == 1 ]] && sudo_options=()
  if ! sudo "${sudo_options[@]}" cp "$hosts_without_block" "$HOSTS_FILE"; then
    echo "Could not remove the Lab 1 host aliases without interactive sudo." >&2
    rm -f "$hosts_without_block"
    return
  fi
  rm -f "$hosts_without_block"
  echo "Removed Lab 1 hostnames from $HOSTS_FILE"
}

create() {
  for vm_name in "${VM_NAMES[@]}"; do
    if instance_exists "$vm_name"; then
      echo "Starting existing VM: $vm_name"
    else
      echo "Creating VM: $vm_name"
      limactl create --tty=false --name="$vm_name" \
        --cpus="$VM_CPUS" --memory="$VM_MEMORY_GIB" --disk="$VM_DISK_GIB" \
        --mount-none --network="$LIMA_NETWORK" "$LIMA_TEMPLATE"
    fi
    limactl start --tty=false "$vm_name"
  done
  configure_hostnames
}

destroy() {
  remove_hostnames
  for vm_name in "${VM_NAMES[@]}"; do
    if instance_exists "$vm_name"; then
      echo "Deleting VM and disk: $vm_name"
      limactl delete --tty=false --force "$vm_name"
    else
      echo "VM does not exist, skipping: $vm_name"
    fi
  done
  rm -f "$ENV_FILE"
}

status() {
  for vm_name in "${VM_NAMES[@]}"; do
    if instance_exists "$vm_name"; then
      limactl list --format table "$vm_name"
    else
      echo "Not created: $vm_name"
    fi
  done
}

main() {
  require_lima
  case "${1:-}" in
    create) require_network; create ;;
    destroy) LAB1_INTERACTIVE_SUDO=1 destroy ;;
    status) status ;;
    hostnames) require_network; LAB1_INTERACTIVE_SUDO=1 configure_hostnames ;;
    *) usage; exit 2 ;;
  esac
}

main "$@"
