#!/usr/bin/env bash
set -euo pipefail

readonly SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly VM_NAMES=(lab2-pg1 lab2-pg2 lab2-pg3)
readonly VM_HOSTNAMES=(pg1.lab2.example pg2.lab2.example pg3.lab2.example)
# The application runs on its own VM rather than on macOS, so the client is
# exercised across the network like a real one -- and so PostgreSQL can pin a
# TLS 1.3 floor, which .NET on macOS cannot negotiate at all.
readonly APP_VM=lab2-app1
readonly APP_HOSTNAME=app1.lab2.example
readonly APP_CPUS="${APP_CPUS:-2}"
readonly APP_MEMORY_GIB="${APP_MEMORY_GIB:-2}"
readonly APP_DISK_GIB="${APP_DISK_GIB:-15}"
readonly VM_CPUS="${VM_CPUS:-2}"
readonly VM_MEMORY_GIB="${VM_MEMORY_GIB:-4}"
readonly VM_DISK_GIB="${VM_DISK_GIB:-20}"
# Data volumes, one per service. The sizes must differ from each other and from
# the root disk: the guest identifies which device is which by size, because
# attachment order is not a contract.
readonly VM_PGDATA_GIB="${VM_PGDATA_GIB:-10}"
readonly VM_ETCD_GIB="${VM_ETCD_GIB:-5}"
readonly LIMA_TEMPLATE="${LIMA_TEMPLATE:-$SCRIPT_DIR/../rocky-9.8.yaml}"
readonly LIMA_NETWORK="${LIMA_NETWORK:-lima:shared}"
readonly ENV_FILE="$SCRIPT_DIR/../.env"
readonly HOSTS_FILE="/etc/hosts"
readonly HOSTS_BEGIN="# BEGIN simple-patroni-npgsql-lab lab2"
readonly HOSTS_END="# END simple-patroni-npgsql-lab lab2"

usage() {
  cat <<'EOF'
Usage: ./scripts/vms.sh create|destroy|status|hostnames

create   Create (if needed) and start lab2-pg1, lab2-pg2, lab2-pg3, and lab2-app1.
destroy  Permanently delete those four VMs and their disks.
status   Display the Lima status of the Lab 2 VMs.
hostnames  Update the marked Lab 2 block in macOS /etc/hosts.

Optional environment overrides:
  VM_CPUS=2 VM_MEMORY_GIB=4 VM_DISK_GIB=20 LIMA_TEMPLATE=rocky-9.8.yaml
  LIMA_NETWORK=lima:shared
EOF
}

require_lima() {
  command -v limactl >/dev/null 2>&1 || {
    echo "limactl is required. Install Lima first: brew install lima" >&2
    exit 1
  }
}

require_network() {
  if [[ "$LIMA_NETWORK" == "lima:shared" ]] && ! limactl sudoers --check >/dev/null 2>&1; then
    echo "Lima's shared socket_vmnet network is not configured." >&2
    echo "Follow https://lima-vm.io/docs/config/network/vmnet/ and rerun this command." >&2
    exit 1
  fi
}

instance_exists() {
  limactl list --quiet | grep -Fxq "$1"
}

disk_exists() {
  limactl disk ls 2>/dev/null | awk 'NR>1 {print $1}' | grep -Fxq "$1"
}

# Lima disks are independent objects, so they are created before the instance
# that references them and deleted after it is gone.
ensure_disk() {
  local name="$1" gib="$2"
  if disk_exists "$name"; then
    echo "Disk already exists: $name"
  else
    echo "Creating disk: $name (${gib}GiB)"
    limactl disk create "$name" --size "${gib}GiB" >/dev/null
  fi
}

data_disks_for() {
  printf '%s-pgdata %s-etcd\n' "$1" "$1"
}

vm_ip() {
  local vm_name="$1" address=""

  # limactl start returns before the shared network has necessarily leased an
  # address, and an empty value here only fails much later in the inventory.
  for _ in {1..30}; do
    address="$(limactl shell --tty=false "$vm_name" sh -ceu \
      'ip -4 -o addr show dev lima0 | grep -oE "[0-9.]+/[0-9]+" | cut -d/ -f1' 2>/dev/null || true)"
    if [[ -n "$address" ]]; then
      printf '%s\n' "$address"
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for a lima0 shared-network address on $vm_name" >&2
  return 1
}

write_env_file() {
  local app_ip="$1"; shift
  local -a vm_ips=("$@")

  {
    printf '%s\n' '# Generated by scripts/vms.sh. Do not commit this file.'
    printf '%s\n' 'PGPORT=5432'
    for index in "${!VM_NAMES[@]}"; do
      printf 'PG%d_HOST=%s\n' "$((index + 1))" "${VM_HOSTNAMES[index]}"
      printf 'PG%d_IP=%s\n' "$((index + 1))" "${vm_ips[index]}"
    done
    printf 'PGHOSTS=%s:5432,%s:5432,%s:5432\n' \
      "${VM_HOSTNAMES[0]}" "${VM_HOSTNAMES[1]}" "${VM_HOSTNAMES[2]}"
    printf 'APP1_HOST=%s\n' "$APP_HOSTNAME"
    printf 'APP1_IP=%s\n' "$app_ip"
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  echo "Wrote connection details: $ENV_FILE"
}

rewrite_hosts_without_lab_block() {
  local destination="$1"
  awk -v begin="$HOSTS_BEGIN" -v end="$HOSTS_END" '
    $0 == begin { in_block = 1; next }
    $0 == end { in_block = 0; next }
    !in_block { print }
  ' "$HOSTS_FILE" > "$destination"
}

configure_hostnames() {
  local -a vm_ips=()
  local index vm_name hosts_without_block updated_hosts

  for vm_name in "${VM_NAMES[@]}"; do
    vm_ips+=("$(vm_ip "$vm_name")")
  done
  write_env_file "$(vm_ip "$APP_VM")" "${vm_ips[@]}"

  hosts_without_block="$(mktemp "${TMPDIR:-/tmp}/lab2-hosts.XXXXXX")"
  updated_hosts="$(mktemp "${TMPDIR:-/tmp}/lab2-hosts-updated.XXXXXX")"
  rewrite_hosts_without_lab_block "$hosts_without_block"
  {
    cat "$hosts_without_block"
    printf '\n%s\n' "$HOSTS_BEGIN"
    for index in "${!VM_NAMES[@]}"; do
      printf '%s %s\n' "${vm_ips[index]}" "${VM_HOSTNAMES[index]}"
    done
    printf '%s %s\n' "$(vm_ip "$APP_VM")" "$APP_HOSTNAME"
    printf '%s\n' "$HOSTS_END"
  } > "$updated_hosts"
  local -a sudo_options=(-n)
  [[ "${LAB2_INTERACTIVE_SUDO:-0}" == 1 ]] && sudo_options=()
  if sudo "${sudo_options[@]}" cp "$updated_hosts" "$HOSTS_FILE"; then
    echo "Configured hostnames: ${VM_HOSTNAMES[*]}"
  else
    echo "Host aliases were not changed because macOS sudo needs an interactive password." >&2
    echo "Run 'make configure_hostnames' from a terminal when you want to add them." >&2
  fi
  rm -f "$hosts_without_block" "$updated_hosts"
}

remove_hostnames() {
  local hosts_without_block

  if ! grep -Fqx "$HOSTS_BEGIN" "$HOSTS_FILE"; then
    return
  fi
  hosts_without_block="$(mktemp "${TMPDIR:-/tmp}/lab2-hosts.XXXXXX")"
  rewrite_hosts_without_lab_block "$hosts_without_block"
  local -a sudo_options=(-n)
  [[ "${LAB2_INTERACTIVE_SUDO:-0}" == 1 ]] && sudo_options=()
  if ! sudo "${sudo_options[@]}" cp "$hosts_without_block" "$HOSTS_FILE"; then
    echo "Could not remove the Lab 2 host aliases without interactive sudo." >&2
    rm -f "$hosts_without_block"
    return
  fi
  rm -f "$hosts_without_block"
  echo "Removed Lab 2 hostnames from $HOSTS_FILE"
}

create() {
  for vm_name in "${VM_NAMES[@]}"; do
    if instance_exists "$vm_name"; then
      echo "Starting existing VM: $vm_name"
    else
      echo "Creating VM: $vm_name"
      ensure_disk "${vm_name}-pgdata" "$VM_PGDATA_GIB"
      ensure_disk "${vm_name}-etcd" "$VM_ETCD_GIB"
      limactl create --tty=false --name="$vm_name" \
        --cpus="$VM_CPUS" --memory="$VM_MEMORY_GIB" --disk="$VM_DISK_GIB" \
        --mount-none --network="$LIMA_NETWORK" \
        --set ".additionalDisks = [{\"name\":\"${vm_name}-pgdata\"},{\"name\":\"${vm_name}-etcd\"}]" \
        "$LIMA_TEMPLATE"
    fi
    limactl start --tty=false "$vm_name"
  done

  if instance_exists "$APP_VM"; then
    echo "Starting existing VM: $APP_VM"
  else
    echo "Creating VM: $APP_VM (application host, no data disks)"
    limactl create --tty=false --name="$APP_VM" \
      --cpus="$APP_CPUS" --memory="$APP_MEMORY_GIB" --disk="$APP_DISK_GIB" \
      --mount-none --network="$LIMA_NETWORK" "$LIMA_TEMPLATE"
  fi
  limactl start --tty=false "$APP_VM"

  configure_hostnames
}

destroy() {
  remove_hostnames
  if instance_exists "$APP_VM"; then
    echo "Deleting VM: $APP_VM"
    limactl delete --tty=false --force "$APP_VM"
  fi
  for vm_name in "${VM_NAMES[@]}"; do
    if instance_exists "$vm_name"; then
      echo "Deleting VM and disk: $vm_name"
      limactl delete --tty=false --force "$vm_name"
    else
      echo "VM does not exist, skipping: $vm_name"
    fi
  done

  # Only now: Lima refuses to delete a disk that is attached to an instance.
  local disk_name
  for vm_name in "${VM_NAMES[@]}"; do
    for disk_name in $(data_disks_for "$vm_name"); do
      if disk_exists "$disk_name"; then
        echo "Deleting data disk: $disk_name"
        limactl disk delete "$disk_name" >/dev/null
      fi
    done
  done
  for vm_name in "${VM_NAMES[@]}"; do
    for disk_name in $(data_disks_for "$vm_name"); do
      if disk_exists "$disk_name"; then
        echo "Data disk still present after teardown: $disk_name" >&2
        return 1
      fi
    done
  done
  rm -f "$ENV_FILE"
}

status() {
  for vm_name in "${VM_NAMES[@]}"; do
    if instance_exists "$vm_name"; then
      limactl list --format table "$vm_name"
    else
      echo "Not created: $vm_name"
    fi
  done
}

main() {
  require_lima
  case "${1:-}" in
    create) require_network; create ;;
    destroy) LAB2_INTERACTIVE_SUDO=1 destroy ;;
    status) status ;;
    hostnames) require_network; LAB2_INTERACTIVE_SUDO=1 configure_hostnames ;;
    *) usage; exit 2 ;;
  esac
}

main "$@"
